package com.cedricverlinden.banking.constants;

public enum Currency {
    
    EUR("€"),
    USD("$"),
    GBP("£"),
    JPY("¥"),
    AUD("$"),
    CAD("$"),
    CHF("Fr"),
    CNY("¥"),
    SEK("kr"),
    NZD("$"),
    KRW("₩"),
    SGD("$"),
    NOK("kr"),
    MXN("$"),
    INR("₹"),
    RUB("₽"),
    ZAR("R"),
    BRL("R$"),
    TRY("₺"),
    HKD("$"),
    IDR("Rp"),
    MYR("RM"),
    PHP("₱"),
    DKK("kr"),
    CZK("Kč"),
    HUF("Ft"),
    ILS("₪"),
    PLN("zł"),
    THB("฿"),
    TWD("NT$"),
    AED("د.إ"),
    ARS("$"),
    CLP("$"),
    COP("$"),
    EGP("E£"),
    KWD("د.ك"),
    PEN("S/"),
    PKR("₨"),
    SAR("﷼"),
    VND("₫"),
    IQD("ع.د"),
    QAR("﷼"),
    UAH("₴"),
    BHD("ب.د"),
    OMR("﷼"),
    LBP("ل.ل"),
    JOD("د.ا"),
    CRC("₡"),
    HRK("kn"),
    DOP("RD$"),
    ISK("kr"),
    MAD("د.م."),
    BOB("Bs."),
    LKR("Rs"),
    HNL("L"),
    BGN("лв"),
    NIO("C$"),
    GTQ("Q"),
    UYU("$U"),
    PYG("₲"),
    UZS("лв"),
    KZT("₸"),
    AZN("ман"),
    GEL("₾"),
    TMT("m"),
    TJS("ЅМ"),
    MNT("₮"),
    KGS("лв"),
    AFN("؋"),
    MZN("MT"),
    BDT("৳"),
    NPR("रू"),
    LAK("₭"),
    MMK("K"),
    KHR("៛"),
    XAF("FCFA"),
    XOF("CFA");

    public final String symbol;

    Currency(String symbol) {
        this.symbol = symbol;
    }

    public String getSymbol() {
        return symbol;
    }
}
